# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand()

0.25086284732627784

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.randn(25)

array([ 0.34484571,  1.2817343 ,  1.05858243,  1.08794001,  2.63376551,
        0.93824925, -1.96341772,  0.70517753,  1.4797025 ,  0.84593604,
       -0.42993485,  0.37430895, -0.67690932,  0.07675346,  2.48846086,
        0.63580662,  0.93195062,  0.17323903,  0.30828266, -2.00625141,
        0.11911114,  0.60788022,  0.09434664,  1.54033689,  0.9659604 ])

#### Create the following matrix:

In [11]:
np.random.random_sample((10,10))

array([[0.31966484, 0.49868834, 0.53136038, 0.91627611, 0.37798543,
        0.05462615, 0.80844495, 0.74094155, 0.42746829, 0.11882026],
       [0.84466246, 0.46764022, 0.97787419, 0.98571111, 0.05998437,
        0.31056209, 0.93686087, 0.51738535, 0.39548384, 0.80941029],
       [0.35578808, 0.96401025, 0.01701452, 0.52916625, 0.58828028,
        0.51092425, 0.26747461, 0.96733655, 0.12582864, 0.75951792],
       [0.48116372, 0.35655374, 0.14882686, 0.05799084, 0.55786157,
        0.11560296, 0.79567393, 0.52849706, 0.54254214, 0.18625276],
       [0.39273381, 0.27202648, 0.87704739, 0.16009181, 0.98257348,
        0.34845821, 0.55435907, 0.47735698, 0.36991201, 0.83457134],
       [0.91668807, 0.944368  , 0.03729375, 0.81891108, 0.22089225,
        0.86236045, 0.31520821, 0.92329112, 0.89135243, 0.16192221],
       [0.03935431, 0.04178243, 0.84227338, 0.42822301, 0.36929047,
        0.89776693, 0.99563721, 0.39161467, 0.64805072, 0.67826541],
       [0.93133212, 0.22810606, 0.7711996

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
mat[3,4]

20

In [29]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [19]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
mat[4]

array([21, 22, 23, 24, 25])

In [21]:
mat[4]

array([21, 22, 23, 24, 25])

In [23]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [24]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [27]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [28]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!